from MainCore.runcorefp import *
initialize_core()
statements = [
    "Rina's pet cat is named Miko, and he loves to eat tuna.",
    "Sandi was born in Bandung on August 14, 1995.",
    "XTech company was founded in 2018 by Anton and Budi.",
    "Siska's favorite colors for her room decoration are navy blue and white.",
    "The marketing team's evaluation meeting is always held every Tuesday at 10:00 AM.",
    "Budi keeps his black notebook on top of the refrigerator in the kitchen.",
    "The Wi-Fi password for the guest room area is 'Tamu1234!'.",
    "The price of one VIP concert ticket for this weekend's event is Rp 1,500,000.",
    "The distance from the head office building to the nearest train station is 3.5 kilometers.",
    "Andi's family's regular dentist is named Dr. Sarah, who practices at Klinik Sehat.",
    "The flight to Tokyo will board from Terminal 3 at Gate 5.",
    "Budi cannot eat spinach and water spinach due to digestive issues.",
    "The numeric access code to enter the logistics warehouse is 889922.",
    "Maya bought three green apples and two oranges at the main market.",
    "The ideal recommended temperature for storing this red wine is 15 degrees Celsius.",
    "The internal application 'SuperApp' version 2.4 was just released last Friday.",
    "A VIP customer named Mr. Joko always orders an iced Americano without sugar.",
    "The height of Mount Fiktif Peak is 4,230 meters above sea level.",
    "In the Alpha project team, Doni is assigned as the Lead Programmer.",
    "The smart lights in the main meeting room are set to turn off automatically at 9:00 PM.",
    "Mrs. Susi always wears red-framed glasses when reading the newspaper.",
    "The maximum battery capacity of the latest Z series laptop is 8500 mAh.",
    "The Arumanis mango tree in the backyard was planted by grandfather in 2010.",
    "The fire alarm on the 4th floor went off yesterday afternoon due to smoke from the pantry kitchen.",
    "The size of the sports shoes Fajar usually wears for marathon running is 42.",
    "The neighbor's cat named Belang often falls asleep on the hood of my sedan.",
    "The deadline for submitting the monthly financial report to the accounting division is the 5th of every month.",
    "The newly renovated city library building has a total of 5 floors and 2 basements.",
    "Uncle Scrooge keeps his first gold coin in a wooden box under the mattress.",
    "The route of bus service number 45 passes through Sudirman Street, Thamrin Street, and ends at Blok M.",
    "The last queue number for the eye clinic patients today has reached 120.",
    "The official vehicle driven by the CEO is a white Toyota Alphard.",
    "The farewell party for the retiring HR Manager will be held at Bunga Rampai Restaurant.",
    "Aunt Ratna's husband is named Uncle Hendra, who currently works as an independent architect.",
    "The minimum sales target for the Surabaya branch this month is set at 500 units.",
    "The presentation file for the third quarter is saved in the 'Q3_Report' folder on drive D.",
    "The recipe for making pandan sponge cake requires 4 eggs and 200 grams of wheat flour as the main ingredients.",
    "The operational working hours for the night shift employees start at 10:00 PM and end at 6:00 AM.",
    "The documentary film 'The Time Explorer' won 5 Oscar awards at this year's event.",
    "The codename for the secret project being developed by the R&D team is 'Project Phoenix'.",
    "Andi has a history of severe allergies to peanuts and seafood.",
    "The company's 15th-anniversary celebration next month will feature a performance by Sheila on 7.",
    "The new uniforms distributed for the restaurant's operational staff are maroon and black.",
    "The first child of the Wijaya family is currently pursuing an undergraduate degree at the University of Indonesia.",
    "The budget for the digital marketing campaign next month was approved to be increased by 20%.",
    "The spare keys to the company's main safe are held only by the Finance Manager and the Operations Director.",
    "The decorative cactus placed near the office window only needs to be watered once every two weeks.",
    "The new official vehicle license plate used by the Sub-district Head is B 1234 KAA.",
    "The orientation training session for new employees will be facilitated directly by Mr. Hendro from the HR division.",
    "The monthly internet quota provided by the company to all field team members is 50 GB."
]
new_statements = [
    "The central park opens at 6:00 AM and closes at 10:00 PM daily.",
    "Charlie's favorite guitar is a red Fender Stratocaster made in 1998.",
    "The new software update requires 45 GB of free disk space to install.",
    "The next solar eclipse will be visible in South America on July 2nd.",
    "Diana's recipe for chocolate chip cookies uses brown sugar and vanilla extract.",
    "The highest grossing movie of 2023 was a sci-fi thriller called 'Beyond the Stars'.",
    "The marathon winner finished the race in exactly 2 hours and 15 minutes.",
    "The password for the secure server is updated every 90 days.",
    "The blue whale can consume up to 4 tons of krill in a single day.",
    "The Eiffel Tower in Paris was completed in the year 1889.",
    "Mr. Smith's flight to London departs from Gate 12 at 4:30 PM.",
    "The local library received a donation of 500 historical books yesterday.",
    "The temperature in the server room must be maintained at 18 degrees Celsius.",
    "Grace's graduation ceremony will be held in the grand auditorium on Friday.",
    "The recipe for the traditional pasta sauce includes garlic, tomatoes, and basil.",
    "The company's annual revenue increased by 15 percent in the last fiscal year.",
    "The nearest gas station is located 5 miles down the highway on the left.",
    "The main character in the novel 'Shadows of Time' is named Arthur Pendragon.",
    "The upcoming tech conference will take place in Las Vegas from November 10 to 12.",
    "The speed limit on the newly constructed highway is 80 miles per hour.",
    "The art gallery is hosting an exhibition of modern sculptures this weekend.",
    "Jack bought a vintage motorcycle for 5,000 dollars at an auction.",
    "The recommended daily water intake for an adult is 2.5 liters.",
    "The local bakery is famous for its sourdough bread baked fresh every morning.",
    "The soccer team practices every Monday and Wednesday at the community field.",
    "The default PIN code for the new security system is 123456.",
    "The highest mountain in Africa is Mount Kilimanjaro, located in Tanzania.",
    "The project deadline was extended by two weeks due to unexpected delays.",
    "The museum is closed on Mondays for maintenance and cleaning.",
    "The concert tickets sold out in just 15 minutes after being released online.",
    "The recommended tire pressure for the sedan is 32 PSI.",
    "The coffee machine in the breakroom requires descaling once a month.",
    "The documentary about deep sea exploration won three awards at the film festival.",
    "The next board meeting is scheduled for the first Thursday of the month.",
    "The ancient ruins were discovered by archaeologists in 1922.",
    "The new shopping mall features over 200 retail stores and a giant aquarium.",
    "The capital city of Australia is Canberra.",
    "The recipe for the perfect omelet requires three eggs and a splash of milk.",
    "The software bug was finally fixed in version 3.1.4.",
    "The train to Edinburgh leaves from platform 9 at exactly 8:45 AM.",
    "The final exam for the physics course will cover chapters 5 through 10.",
    "The gardening club meets every Saturday morning at the botanical garden.",
    "The maximum weight limit for the passenger elevator is 1000 kilograms.",
    "The novel was translated into 20 different languages within a year of its release.",
    "The battery life of the new smartphone is estimated to be up to 48 hours.",
    "The recipe for the spicy curry uses coconut milk and green chilies.",
    "The next Olympic Games will be held in the city of Los Angeles.",
    "The password for the admin account must contain at least 12 characters and a symbol.",
    "The rarest stamp in the collection was printed in the year 1840.",
    "The local farmer's market is open every Sunday from 8:00 AM to 1:00 PM.",
    "The temperature drops below freezing during the winter months in this region.",
    "The famous painting 'Starry Night' was created by Vincent van Gogh.",
    "The new fitness center offers classes in yoga, pilates, and weightlifting.",
    "The delivery driver is expected to arrive between 2:00 PM and 4:00 PM.",
    "The main ingredient in traditional guacamole is ripe avocados.",
    "The company headquarters is located in the heart of the financial district.",
    "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
    "The final chapter of the book reveals the true identity of the villain.",
    "The annual music festival attracts over 50,000 visitors each year.",
    "The recipe for the chocolate cake calls for half a cup of cocoa powder.",
    "The new bridge connecting the two cities will be completed next spring.",
    "The minimum age requirement for the driving test is 17 years old.",
    "The documentary series explores the history of ancient civilizations.",
    "The CEO announced a new initiative to reduce carbon emissions by 30 percent.",
    "The local animal shelter is currently caring for 45 dogs and 30 cats.",
    "The recipe for the classic margarita includes tequila, lime juice, and triple sec.",
    "The longest river in the world is the Nile River.",
    "The software company employs over 500 engineers globally.",
    "The next train to Paris will depart from platform 4.",
    "The historical monument was restored to its original condition in 2015.",
    "The recommended cooking time for a medium-rare steak is 4 minutes per side.",
    "The new security protocol requires two-factor authentication for all users.",
    "The final match of the tennis tournament will be played on Sunday afternoon.",
    "The local theater is putting on a production of 'Hamlet' next month.",
    "The recipe for the fruit smoothie includes bananas, strawberries, and yogurt.",
    "The company's stock price hit an all-time high on Wednesday.",
    "The deepest part of the ocean is the Mariana Trench.",
    "The new smartphone model features a 108-megapixel camera.",
    "The next flight to New York is delayed by two hours due to bad weather.",
    "The ancient artifact was carbon-dated to be over 3,000 years old.",
    "The recommended amount of sleep for an adult is 7 to 9 hours per night.",
    "The new highway extension will reduce travel time by 20 minutes.",
    "The documentary film focuses on the effects of climate change on polar bears.",
    "The board of directors approved the budget for the new research facility.",
    "The local community center is hosting a charity bake sale on Saturday.",
    "The recipe for the chicken soup calls for carrots, celery, and onions.",
    "The largest planet in our solar system is Jupiter.",
    "The software development team uses an agile methodology for project management.",
    "The next bus to the city center arrives at 10:15 AM.",
    "The historical document was signed on July 4, 1776.",
    "The recommended resting heart rate for a healthy adult is between 60 and 100 beats per minute.",
    "The new sports stadium has a seating capacity of 80,000 people.",
    "The documentary series won an Emmy award for outstanding cinematography.",
    "The company's new product line will be officially launched in September.",
    "The local park features a large playground, a duck pond, and walking trails.",
    "The recipe for the beef stew requires slow cooking for at least 4 hours.",
    "The smallest country in the world is Vatican City.",
    "The software application is compatible with both iOS and Android operating systems.",
    "The next ferry to the island departs at noon.",
    "The historical museum is offering free admission on the first Sunday of the month."
]

statements.extend(new_statements)
for text in statements:
    Main_Core_FP_Function(text)

print("test complete")
