from MainCore.runcorefp import *
initialize_core()
# Kode warna teks (Foreground)
MERAH = '\033[31m'
HIJAU = '\033[32m'
KUNING = '\033[33m'
BIRU = '\033[34m'
RESET = '\033[0m'
TEBAL = '\033[1m'

questions = [
    "What is the name of Rina's pet cat, and what is its favorite food?",
    "When and where was Sandi born?",
    "Who are the founders of XTech company, and in what year was it founded?",
    "What are Siska's favorite colors for her room decoration?",
    "When is the marketing team's routine evaluation meeting scheduled?",
    "Where does Budi keep his black notebook?",
    "What is the Wi-Fi password for the guest room area?",
    "How much does one VIP ticket cost for this weekend's concert?",
    "What is the distance between the head office and the nearest train station?",
    "What is the name of Andi's family's regular dentist?",
    "From which terminal and gate will the flight to Tokyo board?",
    "What vegetables can Budi not eat?",
    "What is the access code required to enter the logistics warehouse?",
    "How many and what types of fruit did Maya buy at the market?",
    "What is the ideal temperature for storing this red wine?",
    "What version of the 'SuperApp' application was just released last week?",
    "What drink does the VIP customer named Mr. Joko always order?",
    "What is the height of Mount Fiktif Peak in meters?",
    "What is Doni's position or role in the Alpha project team?",
    "At what time will the lights in the main meeting room turn off automatically?",
    "What color are the frames of the glasses Mrs. Susi wears when reading?",
    "What is the maximum battery capacity for the Z series laptop?",
    "In what year was the mango tree in the backyard planted?",
    "What caused the fire alarm on the 4th floor to go off yesterday afternoon?",
    "What is Fajar's sports shoe size?",
    "Where does the neighbor's cat named Belang often fall asleep?",
    "What date is the maximum deadline for submitting the monthly financial report?",
    "How many floors and basements does the city library building have?",
    "Where does Uncle Scrooge keep his first gold coin?",
    "Which streets does the route of bus number 45 pass through?",
    "What is the last queue number at the eye clinic today?",
    "What is the make and color of the CEO's official vehicle?",
    "At which restaurant is the HR Manager's farewell party being held?",
    "What is the name of Aunt Ratna's husband, and what is his profession?",
    "What is the minimum sales target this month for the Surabaya branch?",
    "Where is the third-quarter presentation file located?",
    "How many eggs and how much wheat flour are needed to make a pandan sponge cake?",
    "What time does the night shift for employees start and end?",
    "How many Oscar awards did the film 'The Time Explorer' win?",
    "What is the codename of the secret project being worked on by the R&D team?",
    "What foods trigger Andi's allergies?",
    "Which artist or band will perform at the company's 15th-anniversary celebration?",
    "What is the color combination of the new uniforms for the restaurant's operational staff?",
    "At which university is the first child of the Wijaya family studying?",
    "By what percentage is the budget for next month's digital marketing campaign increasing?",
    "Who holds the spare keys to the company's main safe?",
    "How often does the decorative cactus near the window need to be watered?",
    "What is the license plate number of the new official vehicle used by the Sub-district Head?",
    "Who will facilitate the orientation training session for new employees?",
    "What is the amount of the monthly internet quota provided to field team members?"
]

canswers = [
    ["miko", "tuna"],
    ["bandung", "august 14", "1995"],
    ["anton", "budi", "2018"],
    ["navy blue", "white"],
    ["tuesday", "10:00"],
    ["refrigerator", "kitchen"],
    ["tamu1234!"],
    ["1,500,000"],
    ["3.5"],
    ["sarah", "sehat"],
    ["terminal 3", "gate 5"],
    ["spinach", "water spinach"],
    ["889922"],
    ["three", "green apples", "two", "oranges"],
    ["15"],
    ["2.4"],
    ["iced americano", "without sugar"],
    ["4,230"],
    ["lead programmer"],
    ["9:00", "pm"],
    ["red"],
    ["8500"],
    ["2010"],
    ["smoke", "pantry"],
    ["42"],
    ["hood", "sedan"],
    ["5th"],
    ["5 floors", "2 basements"],
    ["wooden box", "under the mattress"],
    ["sudirman", "thamrin", "blok m"],
    ["120"],
    ["white", "toyota alphard"],
    ["bunga rampai"],
    ["hendra", "architect"],
    ["500"],
    ["q3_report", "drive d"],
    ["4", "eggs", "200", "wheat flour"],
    ["10:00 pm", "6:00 am"],
    ["5"],
    ["project phoenix"],
    ["peanuts", "seafood"],
    ["sheila on 7"],
    ["maroon", "black"],
    ["university of indonesia"],
    ["20"],
    ["finance manager", "operations director"],
    ["two weeks"],
    ["b 1234 kaa"],
    ["hendro", "hr"],
    ["50"]
]
new_questions = [
    "What time does the central park open and close daily?",
    "What is the brand, color, and year of Charlie's favorite guitar?",
    "How much free disk space is required to install the new software update?",
    "Where and when will the next solar eclipse be visible?",
    "What are the key ingredients in Diana's recipe for chocolate chip cookies?",
    "What is the title and genre of the highest grossing movie of 2023?",
    "How long did it take for the marathon winner to finish the race?",
    "How often is the password for the secure server updated?",
    "How much krill can a blue whale consume in a single day?",
    "In what year was the Eiffel Tower in Paris completed?",
    "From which gate and at what time does Mr. Smith's flight to London depart?",
    "How many and what type of books did the local library receive yesterday?",
    "At what temperature must the server room be maintained?",
    "Where and when will Grace's graduation ceremony be held?",
    "What ingredients are included in the recipe for the traditional pasta sauce?",
    "By what percentage did the company's annual revenue increase in the last fiscal year?",
    "How far and in what direction is the nearest gas station located?",
    "What is the name of the main character in the novel 'Shadows of Time'?",
    "Where and when will the upcoming tech conference take place?",
    "What is the speed limit on the newly constructed highway?",
    "What type of exhibition is the art gallery hosting this weekend?",
    "What did Jack buy at an auction, and how much did it cost?",
    "What is the recommended daily water intake for an adult?",
    "What is the local bakery famous for, and when is it baked?",
    "When and where does the soccer team practice?",
    "What is the default PIN code for the new security system?",
    "What is the highest mountain in Africa, and where is it located?",
    "By how long was the project deadline extended due to unexpected delays?",
    "On which day is the museum closed, and for what reason?",
    "How quickly did the concert tickets sell out after being released online?",
    "What is the recommended tire pressure for the sedan?",
    "How often does the coffee machine in the breakroom require descaling?",
    "How many awards did the deep sea exploration documentary win at the film festival?",
    "When is the next board meeting scheduled?",
    "In what year were the ancient ruins discovered by archaeologists?",
    "How many retail stores and what special feature does the new shopping mall have?",
    "What is the capital city of Australia?",
    "How many eggs and what other ingredient are needed for the perfect omelet?",
    "In which version was the software bug finally fixed?",
    "From which platform and at what time does the train to Edinburgh leave?",
    "Which chapters will the final exam for the physics course cover?",
    "When and where does the gardening club meet?",
    "What is the maximum weight limit for the passenger elevator?",
    "Into how many languages was the novel translated within a year of its release?",
    "What is the estimated battery life of the new smartphone?",
    "What ingredients are used in the recipe for the spicy curry?",
    "In which city will the next Olympic Games be held?",
    "What are the requirements for the admin account password?",
    "In what year was the rarest stamp in the collection printed?",
    "When is the local farmer's market open?",
    "What happens to the temperature during the winter months in this region?",
    "Who created the famous painting 'Starry Night'?",
    "What classes does the new fitness center offer?",
    "Between what times is the delivery driver expected to arrive?",
    "What is the main ingredient in traditional guacamole?",
    "Where is the company headquarters located?",
    "What is the approximate speed of light in a vacuum?",
    "What is revealed in the final chapter of the book?",
    "How many visitors does the annual music festival attract each year?",
    "How much cocoa powder does the recipe for the chocolate cake call for?",
    "When will the new bridge connecting the two cities be completed?",
    "What is the minimum age requirement for the driving test?",
    "What topic does the documentary series explore?",
    "By what percentage did the CEO announce a new initiative to reduce carbon emissions?",
    "How many dogs and cats is the local animal shelter currently caring for?",
    "What ingredients are included in the recipe for the classic margarita?",
    "What is the longest river in the world?",
    "How many engineers does the software company employ globally?",
    "From which platform will the next train to Paris depart?",
    "In what year was the historical monument restored to its original condition?",
    "What is the recommended cooking time per side for a medium-rare steak?",
    "What does the new security protocol require for all users?",
    "When will the final match of the tennis tournament be played?",
    "What production is the local theater putting on next month?",
    "What fruits are included in the recipe for the fruit smoothie?",
    "When did the company's stock price hit an all-time high?",
    "What is the deepest part of the ocean?",
    "What is the megapixel count of the new smartphone model's camera?",
    "Why is the next flight to New York delayed, and by how long?",
    "How old was the ancient artifact carbon-dated to be?",
    "What is the recommended amount of sleep for an adult per night?",
    "By how many minutes will the new highway extension reduce travel time?",
    "What animal and topic does the documentary film focus on?",
    "What did the board of directors approve the budget for?",
    "What event is the local community center hosting on Saturday?",
    "What vegetables does the recipe for the chicken soup call for?",
    "What is the largest planet in our solar system?",
    "What methodology does the software development team use for project management?",
    "At what time does the next bus to the city center arrive?",
    "On what date was the historical document signed?",
    "What is the recommended resting heart rate range for a healthy adult?",
    "What is the seating capacity of the new sports stadium?",
    "For what did the documentary series win an Emmy award?",
    "In which month will the company's new product line be officially launched?",
    "What features does the local park have?",
    "How long does the recipe for the beef stew require for slow cooking?",
    "What is the smallest country in the world?",
    "With which operating systems is the software application compatible?",
    "At what time does the next ferry to the island depart?",
    "On which day does the historical museum offer free admission?"
]

new_canswers = [
    ["6:00 am", "10:00 pm"],
    ["fender stratocaster", "red", "1998"],
    ["45 gb"],
    ["south america", "july 2nd"],
    ["brown sugar", "vanilla extract"],
    ["beyond the stars", "sci-fi thriller"],
    ["2 hours", "15 minutes"],
    ["90 days"],
    ["4 tons"],
    ["1889"],
    ["gate 12", "4:30 pm"],
    ["500", "historical"],
    ["18 degrees celsius"],
    ["grand auditorium", "friday"],
    ["garlic", "tomatoes", "basil"],
    ["15 percent"],
    ["5 miles", "left"],
    ["arthur pendragon"],
    ["las vegas", "november 10", "12"],
    ["80 miles per hour"],
    ["modern sculptures"],
    ["vintage motorcycle", "5,000"],
    ["2.5 liters"],
    ["sourdough bread", "morning"],
    ["monday", "wednesday", "community field"],
    ["123456"],
    ["mount kilimanjaro", "tanzania"],
    ["two weeks"],
    ["mondays", "maintenance", "cleaning"],
    ["15 minutes"],
    ["32 psi"],
    ["once a month"],
    ["three"],
    ["first thursday"],
    ["1922"],
    ["200", "giant aquarium"],
    ["canberra"],
    ["three eggs", "milk"],
    ["3.1.4"],
    ["platform 9", "8:45 am"],
    ["chapters 5", "10"],
    ["saturday morning", "botanical garden"],
    ["1000 kilograms"],
    ["20"],
    ["48 hours"],
    ["coconut milk", "green chilies"],
    ["los angeles"],
    ["12 characters", "symbol"],
    ["1840"],
    ["sunday", "8:00 am", "1:00 pm"],
    ["drops below freezing"],
    ["vincent van gogh"],
    ["yoga", "pilates", "weightlifting"],
    ["2:00 pm", "4:00 pm"],
    ["ripe avocados"],
    ["financial district"],
    ["299,792"],
    ["true identity", "villain"],
    ["50,000"],
    ["half a cup"],
    ["next spring"],
    ["17"],
    ["ancient civilizations"],
    ["30 percent"],
    ["45 dogs", "30 cats"],
    ["tequila", "lime juice", "triple sec"],
    ["nile river"],
    ["500"],
    ["platform 4"],
    ["2015"],
    ["4 minutes"],
    ["two-factor authentication"],
    ["sunday afternoon"],
    ["hamlet"],
    ["bananas", "strawberries", "yogurt"],
    ["wednesday"],
    ["mariana trench"],
    ["108-megapixel"],
    ["bad weather", "two hours"],
    ["3,000 years"],
    ["7 to 9 hours"],
    ["20 minutes"],
    ["polar bears", "climate change"],
    ["new research facility"],
    ["charity bake sale"],
    ["carrots", "celery", "onions"],
    ["jupiter"],
    ["agile methodology"],
    ["10:15 am"],
    ["july 4, 1776"],
    ["60 and 100"],
    ["80,000"],
    ["outstanding cinematography"],
    ["september"],
    ["playground", "duck pond", "walking trails"],
    ["4 hours"],
    ["vatican city"],
    ["ios", "android"],
    ["noon"],
    ["first sunday"]
]

questions.extend(new_questions)
canswers.extend(new_canswers)
def evaluate_answer(generated_answer, expected_keywords):
    gen_ans_lower = str(generated_answer).lower()
    for keyword in expected_keywords:
        if keyword.lower() not in gen_ans_lower:
            return 0 
    return 1
Nilai = 0
scores = []

print("=== STARTING MEMORY TEST ===")

for i, (question, keywords) in enumerate(zip(questions, canswers), 1):
    generated_answer = Main_Core_FP_Function(question)
    
    score = evaluate_answer(generated_answer, keywords)
    scores.append(score)
    Nilai += score
    
    status = f"{HIJAU}SUCCESS (1){RESET}" if score == 1 else f"{MERAH}{TEBAL}FAILED  (0){RESET}"
    print(f"Test {i:02d}: {status}")

print("============================")
print("Test Complete")
print(f"Total Score: {Nilai} / {len(questions)}")
