from MainCore.runcorefp import *
initialize_core()
statements = [
    "Rina's pet cat is named Miko, and he loves to eat tuna.",
    "Sandi was born in Bandung on August 14, 1995.",
    "XTech company was founded in 2018 by Anton and Budi.",
    "Siska's favorite colors for her room decoration are navy blue and white.",
    "The marketing team's evaluation meeting is always held every Tuesday at 10:00 AM.",
    "Budi keeps his black notebook on top of the refrigerator in the kitchen.",
    "The Wi-Fi password for the guest room area is 'Tamu1234!'.",
    "The price of one VIP concert ticket for this weekend's event is Rp 1,500,000.",
    "The distance from the head office building to the nearest train station is 3.5 kilometers.",
    "Andi's family's regular dentist is named Dr. Sarah, who practices at Klinik Sehat.",
    "The flight to Tokyo will board from Terminal 3 at Gate 5.",
    "Budi cannot eat spinach and water spinach due to digestive issues.",
    "The numeric access code to enter the logistics warehouse is 889922.",
    "Maya bought three green apples and two oranges at the main market.",
    "The ideal recommended temperature for storing this red wine is 15 degrees Celsius.",
    "The internal application 'SuperApp' version 2.4 was just released last Friday.",
    "A VIP customer named Mr. Joko always orders an iced Americano without sugar.",
    "The height of Mount Fiktif Peak is 4,230 meters above sea level.",
    "In the Alpha project team, Doni is assigned as the Lead Programmer.",
    "The smart lights in the main meeting room are set to turn off automatically at 9:00 PM.",
    "Mrs. Susi always wears red-framed glasses when reading the newspaper.",
    "The maximum battery capacity of the latest Z series laptop is 8500 mAh.",
    "The Arumanis mango tree in the backyard was planted by grandfather in 2010.",
    "The fire alarm on the 4th floor went off yesterday afternoon due to smoke from the pantry kitchen.",
    "The size of the sports shoes Fajar usually wears for marathon running is 42.",
    "The neighbor's cat named Belang often falls asleep on the hood of my sedan.",
    "The deadline for submitting the monthly financial report to the accounting division is the 5th of every month.",
    "The newly renovated city library building has a total of 5 floors and 2 basements.",
    "Uncle Scrooge keeps his first gold coin in a wooden box under the mattress.",
    "The route of bus service number 45 passes through Sudirman Street, Thamrin Street, and ends at Blok M.",
    "The last queue number for the eye clinic patients today has reached 120.",
    "The official vehicle driven by the CEO is a white Toyota Alphard.",
    "The farewell party for the retiring HR Manager will be held at Bunga Rampai Restaurant.",
    "Aunt Ratna's husband is named Uncle Hendra, who currently works as an independent architect.",
    "The minimum sales target for the Surabaya branch this month is set at 500 units.",
    "The presentation file for the third quarter is saved in the 'Q3_Report' folder on drive D.",
    "The recipe for making pandan sponge cake requires 4 eggs and 200 grams of wheat flour as the main ingredients.",
    "The operational working hours for the night shift employees start at 10:00 PM and end at 6:00 AM.",
    "The documentary film 'The Time Explorer' won 5 Oscar awards at this year's event.",
    "The codename for the secret project being developed by the R&D team is 'Project Phoenix'.",
    "Andi has a history of severe allergies to peanuts and seafood.",
    "The company's 15th-anniversary celebration next month will feature a performance by Sheila on 7.",
    "The new uniforms distributed for the restaurant's operational staff are maroon and black.",
    "The first child of the Wijaya family is currently pursuing an undergraduate degree at the University of Indonesia.",
    "The budget for the digital marketing campaign next month was approved to be increased by 20%.",
    "The spare keys to the company's main safe are held only by the Finance Manager and the Operations Director.",
    "The decorative cactus placed near the office window only needs to be watered once every two weeks.",
    "The new official vehicle license plate used by the Sub-district Head is B 1234 KAA.",
    "The orientation training session for new employees will be facilitated directly by Mr. Hendro from the HR division.",
    "The monthly internet quota provided by the company to all field team members is 50 GB."
]

for text in statements:
    Main_Core_FP_Function(text)

print("Injection test complete")
